version: '3.8'

services:
  php:
    build: ./php

    volumes: 
      - /home/tpuser/web/html:/var/www/html/www:ro

    networks: 
      - Web_network
    env_file:
     - /home/tpuser/db.env

  web:
    build: ./web
    volumes:
      - /home/tpuser/web/config/nginx.conf:/etc/nginx/nginx.conf 
      - /home/tpuser/web/html:/var/www/html/www:ro
    networks: 
      - Web_network
    ports: 
      - "80:80"
  
  dns:
    build: ./tp4
    networks: 
      - Web_network
    ports: 
      - "53:53/tcp"
      - "53:53/udp"

  mariadb:
    build: ./db
    volumes:
    - ./db/sql:/docker-entrypoint-initdb.d
    networks: 
      - Web_network
    env_file:
      - /home/tpuser/db/sql/root.env
      - /home/tpuser/db.env
    

networks:
  Web_network: