version: '3.8'

services:
  php:
    build: ./php

    volumes: 
      - /home/tpuser/web/html:/var/www/html/www:ro

    networks: 
      - Web_network


  web:
    build: ./web
    volumes:
      - /home/tpuser/web/config/nginx.conf:/etc/nginx/nginx.conf 
      - /home/tpuser/web/html:/var/www/html/www:ro
    networks: 
      - Web_network
    ports: 
      - "80:80"
  
  dns:
    build: ./tp4
    networks: 
      - Web_network
    ports: 
      - "53:53/tcp"
      - "53:53/udp"

  mariadb:
    image: mariadb
    volumes:
    - ./db/sql:/docker-entrypoint-initdb.d
    networks: 
      - Web_network
    environment:
     MYSQL_ROOT_PASSWORD: mypass
    

networks:
  Web_network:


